[
{ "model" : 1, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [], "outputactivation" : "sigmoid" },
{ "model" : 2, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [], "outputactivation" : "linear" },
{ "model" : 3, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [], "outputactivation" : "tanh" },
{ "model" : 6, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 10 } ], "outputactivation" : "sigmoid" },
{ "model" : 7, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 25 } ], "outputactivation" : "sigmoid" },
{ "model" : 8, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } ], "outputactivation" : "sigmoid" },
{ "model" : 9, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } ], "outputactivation" : "sigmoid" },
{ "model" : 10, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 150 } ], "outputactivation" : "sigmoid" },
{ "model" : 11, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 200 } ], "outputactivation" : "sigmoid" },
{ "model" : 12, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "sigmoid" },
{ "model" : 13, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "relu", "size" : 50 } ], "outputactivation" : "sigmoid" },
{ "model" : 14, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "sigmoid" },
{ "model" : 15, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "sigmoid" },
{ "model" : 16, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "relu", "size" : 100 } ], "outputactivation" : "sigmoid" },
{ "model" : 17, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } , { "activation" : "relu", "size" : 50 } ], "outputactivation" : "sigmoid" },
{ "model" : 18, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } , { "activation" : "relu", "size" : 100 } ], "outputactivation" : "sigmoid" },
{ "model" : 19, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 50 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "sigmoid" },
{ "model" : 20, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 20 } , { "activation" : "relu", "size" : 50 } ], "outputactivation" : "sigmoid" },
{ "model" : 21, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 20 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "sigmoid" },
{ "model" : 22, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 100 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "sigmoid" },
{ "model" : 23, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 20 } , { "activation" : "relu", "size" : 100 } ], "outputactivation" : "sigmoid" },
{ "model" : 24, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 50 } , { "activation" : "relu", "size" : 50 } ], "outputactivation" : "sigmoid" },
{ "model" : 25, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 100 } , { "activation" : "relu", "size" : 100 } ], "outputactivation" : "sigmoid" },
{ "model" : 26, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } , { "activation" : "sigmoid", "size" : 20 } ], "outputactivation" : "sigmoid" },
{ "model" : 27, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "sigmoid", "size" : 50 } ], "outputactivation" : "sigmoid" },
{ "model" : 28, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "sigmoid", "size" : 20 } ], "outputactivation" : "sigmoid" },
{ "model" : 29, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } , { "activation" : "sigmoid", "size" : 20 } ], "outputactivation" : "sigmoid" },
{ "model" : 30, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "sigmoid", "size" : 100 } ], "outputactivation" : "sigmoid" },
{ "model" : 31, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } , { "activation" : "sigmoid", "size" : 50 } ], "outputactivation" : "sigmoid" },
{ "model" : 32, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } , { "activation" : "sigmoid", "size" : 100 } ], "outputactivation" : "sigmoid" },
{ "model" : 33, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 10 } ], "outputactivation" : "relu" },
{ "model" : 34, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 25 } ], "outputactivation" : "relu" },
{ "model" : 35, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } ], "outputactivation" : "relu" },
{ "model" : 36, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } ], "outputactivation" : "relu" },
{ "model" : 37, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 150 } ], "outputactivation" : "relu" },
{ "model" : 38, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 200 } ], "outputactivation" : "relu" },
{ "model" : 39, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "relu" },
{ "model" : 40, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "relu", "size" : 50 } ], "outputactivation" : "relu" },
{ "model" : 41, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "relu" },
{ "model" : 42, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "relu" },
{ "model" : 43, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "relu", "size" : 100 } ], "outputactivation" : "relu" },
{ "model" : 44, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } , { "activation" : "relu", "size" : 50 } ], "outputactivation" : "relu" },
{ "model" : 45, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } , { "activation" : "relu", "size" : 100 } ], "outputactivation" : "relu" },
{ "model" : 46, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 50 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "relu" },
{ "model" : 47, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 20 } , { "activation" : "relu", "size" : 50 } ], "outputactivation" : "relu" },
{ "model" : 48, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 20 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "relu" },
{ "model" : 49, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 100 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "relu" },
{ "model" : 50, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 20 } , { "activation" : "relu", "size" : 100 } ], "outputactivation" : "relu" },
{ "model" : 51, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 50 } , { "activation" : "relu", "size" : 50 } ], "outputactivation" : "relu" },
{ "model" : 52, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 100 } , { "activation" : "relu", "size" : 100 } ], "outputactivation" : "relu" },
{ "model" : 53, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } , { "activation" : "sigmoid", "size" : 20 } ], "outputactivation" : "relu" },
{ "model" : 54, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "sigmoid", "size" : 50 } ], "outputactivation" : "relu" },
{ "model" : 55, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "sigmoid", "size" : 20 } ], "outputactivation" : "relu" },
{ "model" : 56, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } , { "activation" : "sigmoid", "size" : 20 } ], "outputactivation" : "relu" },
{ "model" : 57, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "sigmoid", "size" : 100 } ], "outputactivation" : "relu" },
{ "model" : 58, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } , { "activation" : "sigmoid", "size" : 50 } ], "outputactivation" : "relu" },
{ "model" : 59, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } , { "activation" : "sigmoid", "size" : 100 } ], "outputactivation" : "relu" },
{ "model" : 60, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 10 } ], "outputactivation" : "linear" },
{ "model" : 61, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 25 } ], "outputactivation" : "linear" },
{ "model" : 62, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } ], "outputactivation" : "linear" },
{ "model" : 63, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } ], "outputactivation" : "linear" },
{ "model" : 64, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 150 } ], "outputactivation" : "linear" },
{ "model" : 65, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 200 } ], "outputactivation" : "linear" },
{ "model" : 66, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "linear" },
{ "model" : 67, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "relu", "size" : 50 } ], "outputactivation" : "linear" },
{ "model" : 68, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "linear" },
{ "model" : 69, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "linear" },
{ "model" : 70, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "relu", "size" : 100 } ], "outputactivation" : "linear" },
{ "model" : 71, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } , { "activation" : "relu", "size" : 50 } ], "outputactivation" : "linear" },
{ "model" : 72, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } , { "activation" : "relu", "size" : 100 } ], "outputactivation" : "linear" },
{ "model" : 73, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 50 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "linear" },
{ "model" : 74, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 20 } , { "activation" : "relu", "size" : 50 } ], "outputactivation" : "linear" },
{ "model" : 75, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 20 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "linear" },
{ "model" : 76, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 100 } , { "activation" : "relu", "size" : 20 } ], "outputactivation" : "linear" },
{ "model" : 77, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 20 } , { "activation" : "relu", "size" : 100 } ], "outputactivation" : "linear" },
{ "model" : 78, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 50 } , { "activation" : "relu", "size" : 50 } ], "outputactivation" : "linear" },
{ "model" : 79, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "sigmoid", "size" : 100 } , { "activation" : "relu", "size" : 100 } ], "outputactivation" : "linear" },
{ "model" : 80, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } , { "activation" : "sigmoid", "size" : 20 } ], "outputactivation" : "linear" },
{ "model" : 81, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "sigmoid", "size" : 50 } ], "outputactivation" : "linear" },
{ "model" : 82, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "sigmoid", "size" : 20 } ], "outputactivation" : "linear" },
{ "model" : 83, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } , { "activation" : "sigmoid", "size" : 20 } ], "outputactivation" : "linear" },
{ "model" : 84, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 20 } , { "activation" : "sigmoid", "size" : 100 } ], "outputactivation" : "linear" },
{ "model" : 85, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 50 } , { "activation" : "sigmoid", "size" : 50 } ], "outputactivation" : "linear" },
{ "model" : 86, "epochs" : 2000, "optimizer" : "adagrad", "layers" : [ { "activation" : "relu", "size" : 100 } , { "activation" : "sigmoid", "size" : 100 } ], "outputactivation" : "linear" }
]

